language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
    # Tricks to avoid matplotlib error about X11:
    # 'no display name and no $DISPLAY environment variable'
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/#Starting-a-Web-Server
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

install:
  - pip install Cython
  - pip install .
  - pip install pytest-cov

script:
  - pytest --cov ripser

after_success:
  - bash <(curl -s https://codecov.io/bash)